apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nixnamaedu/backend-final:1.1
        name: backend
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend

  ports:
    - port: 80
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: nixnamaedu/pa-frontend
        name: frontend
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend

  ports:
    - port: 8080
      nodePort: 32000
