apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
    name: frontend
spec:
    type: LoadBalancer
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 32000-tcp
      port: 32000
      protocol: TCP
      targetPort: 32000
    selector:
      deploymentconfig: frontend
status:
    loadBalancer: {}
