apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
    name: backend
spec:
    replicas: {{.Values.replicaCount}}
    selector:
      matchLabels:
        deploymentconfig: backend
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: backend
      spec:
        containers:
        - env:
          - name: TZ
            value: Asia/Kolkata
          image:  {{.Values.imagename}}:{{.Values.imagetag}}
          name: backend
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 80
            protocol: TCP
        imagePullSecrets:
        - name: regcred
