apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
    name: backend
spec:
    type: LoadBalancer    
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 31000-tcp
      port: 31000
      protocol: TCP
      targetPort: 31000
    selector:
      deploymentconfig: backend
status:
    loadBalancer: {}
